--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer_datatype
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from customer_datatype
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer_datatype)


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT *
FROM (
    SELECT 
        item_purchased,
        ROUND(AVG(review_rating), 2) AS avg_review_rating
    FROM customer_datatype
    GROUP BY item_purchased
    ORDER BY avg_review_rating DESC
)
WHERE ROWNUM <= 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer_datatype
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_datatype
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT *
FROM (
    SELECT 
        item_purchased,
        ROUND(
            COUNT(CASE 
                    WHEN discount_applied = 'Yes' 
                    THEN 1 
                 END) * 100.0 / COUNT(*),
            2
        ) AS discount_percentage
    FROM customer_datatype
    GROUP BY item_purchased
    ORDER BY discount_percentage DESC
)
WHERE ROWNUM <= 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
SELECT 
    customer_segment,
    COUNT(*) AS customer_count
FROM (
    SELECT 
        customer_id,
        CASE
            WHEN previous_purchases = 0 THEN 'New'
            WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_datatype
)
GROUP BY customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
SELECT *
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        RANK() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS product_rank
    FROM customer_datatype
    GROUP BY category, item_purchased
)
WHERE product_rank <= 3;
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer_datatype
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_datatype
GROUP BY age_group
ORDER BY total_revenue desc;


--Q11. Which products generate the highest total revenue?
SELECT item_purchased,
       SUM(purchase_amount) AS total_revenue
FROM customer_datatype
GROUP BY item_purchased
ORDER BY total_revenue DESC;

--Q12. Which category has the highest average purchase amount?
SELECT category,
       ROUND(AVG(purchase_amount),2) AS avg_purchase
FROM customer_datatype
GROUP BY category
ORDER BY avg_purchase DESC;

--Q13. Which season has the highest sales?
SELECT season,
       SUM(purchase_amount) AS total_sales
FROM customer_datatype
GROUP BY season
ORDER BY total_sales DESC;

--Q14. Find top 10 highest spending customers

select * from (SELECT customer_id,
       SUM(purchase_amount) AS total_spent
FROM customer_datatype
GROUP BY customer_id
ORDER BY total_spent DESC
)
where rownum<=10;

--Q15. Which category receives the lowest ratings?
select * from (SELECT category,
       ROUND(AVG(review_rating),2) AS avg_rating
FROM customer_datatype
GROUP BY category
ORDER BY avg_rating ASC
)where rownum=1;

--Q16. Find top 3 customers in each location
SELECT *
FROM (
    SELECT location,
           customer_id,
           SUM(purchase_amount) AS total_spent,
           RANK() OVER(
               PARTITION BY location
               ORDER BY SUM(purchase_amount) DESC
           ) AS rnk
    FROM customer_datatype
    GROUP BY location,customer_id
)
WHERE rnk <= 3;



